from typing import Optional, Protocol

from bov_data.data import BirdBuddy, Sighting, User


class DB(Protocol):
    async def close(self) -> None: ...

    async def fetch_users(self) -> list[User]: ...

    async def update_user(self, id: str, bird_buddy: Optional[BirdBuddy] = None) -> None: ...

    async def create_sighting(self, sighting: Sighting) -> str: ...

    async def exists_sighting(self, id: str) -> bool: ...
